### ISSUE TITLE
Rename OAuth2 Namespace

### ISSUE THREAD

**Issue by D4rkMindz** [bshaffer/oauth2-server-httpfoundation-bridge#27]
I am creating an API with OAuth2.0. For the Access Grant I use your Library ([bshaffer/oauth2-server-php](https://github.com/bshaffer/oauth2-server-php)). This Library is also in the OAuth2 Namespace. In some cases this can cause a Bug.

**Comment by reb3r** [comment]
This bridge library uses only the OAuth2\HttpFoundationBridge namespace. Therefore I don't see any problems as long as the HttpFoundationBridge namespace is not used in the core library. As both projects are from the same maintainer, there should be no problem.

**Comment by bshaffer** [comment]
There's no issue with namespace conflicts here since, as @reb3r mentioned, this library uses a sub-namespace.
