### ISSUE TITLE
HTTPFoundation doesn't seem to be picking `Authorization` headers...

### ISSUE THREAD

**Issue by julien-c** [bshaffer/oauth2-server-httpfoundation-bridge#3]
so it doesn't work out of the box with `Bearer` type access tokens.

I've tried that on 3 different, stock versions of Apache and `mod_php`.

I've noticed that you had a fix involving `apache_request_headers` here: https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Request.php#L148-L157, would that be the way to go?

**Comment by JSkalskiSBG** [comment]
Other fix for Apache users:
