### ISSUE TITLE
Declaration of OAuth2\HttpFoundationBridge\Request::createFromGlobals() must be compatible with 

### ISSUE THREAD

**Issue by itisxx** [bshaffer/oauth2-server-httpfoundation-bridge#41]
Declaration of OAuth2\HttpFoundationBridge\Request::createFromGlobals() must be compatible with Symfony\Component\HttpFoundation\Request::createFromGlobals(): static

vendor\bshaffer\oauth2-server-httpfoundation-bridge\src\OAuth2\HttpFoundationBridge\**Request.php  line 59**

**Comment by W0rma** [comment]
https://github.com/bshaffer/oauth2-server-httpfoundation-bridge/pull/42 should fix this warning.

**Comment by bshaffer** [comment]
fixed in #42
